/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MesajlarRouteImport } from './routes/mesajlar'
import { Route as YonetimRouteImport } from './routes/yonetim'
import { Route as KategoriCategoryRouteImport } from './routes/kategori.$category'
import { Route as UrunProductIdRouteImport } from './routes/urun.$productId'
import { Route as KatalogCategorySubcategoryRouteImport } from './routes/katalog.$category.$subcategory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MesajlarRoute = MesajlarRouteImport.update({
  id: '/mesajlar',
  path: '/mesajlar',
  getParentRoute: () => rootRouteImport,
} as any)
const YonetimRoute = YonetimRouteImport.update({
  id: '/yonetim',
  path: '/yonetim',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriCategoryRoute = KategoriCategoryRouteImport.update({
  id: '/kategori/$category',
  path: '/kategori/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunProductIdRoute = UrunProductIdRouteImport.update({
  id: '/urun/$productId',
  path: '/urun/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogCategorySubcategoryRoute =
  KatalogCategorySubcategoryRouteImport.update({
    id: '/katalog/$category/$subcategory',
    path: '/katalog/$category/$subcategory',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mesajlar': typeof MesajlarRoute
  '/yonetim': typeof YonetimRoute
  '/kategori/$category': typeof KategoriCategoryRoute
  '/urun/$productId': typeof UrunProductIdRoute
  '/katalog/$category/$subcategory': typeof KatalogCategorySubcategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mesajlar': typeof MesajlarRoute
  '/yonetim': typeof YonetimRoute
  '/kategori/$category': typeof KategoriCategoryRoute
  '/urun/$productId': typeof UrunProductIdRoute
  '/katalog/$category/$subcategory': typeof KatalogCategorySubcategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mesajlar': typeof MesajlarRoute
  '/yonetim': typeof YonetimRoute
  '/kategori/$category': typeof KategoriCategoryRoute
  '/urun/$productId': typeof UrunProductIdRoute
  '/katalog/$category/$subcategory': typeof KatalogCategorySubcategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mesajlar'
    | '/yonetim'
    | '/kategori/$category'
    | '/urun/$productId'
    | '/katalog/$category/$subcategory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mesajlar'
    | '/yonetim'
    | '/kategori/$category'
    | '/urun/$productId'
    | '/katalog/$category/$subcategory'
  id:
    | '__root__'
    | '/'
    | '/mesajlar'
    | '/yonetim'
    | '/kategori/$category'
    | '/urun/$productId'
    | '/katalog/$category/$subcategory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MesajlarRoute: typeof MesajlarRoute
  YonetimRoute: typeof YonetimRoute
  KategoriCategoryRoute: typeof KategoriCategoryRoute
  UrunProductIdRoute: typeof UrunProductIdRoute
  KatalogCategorySubcategoryRoute: typeof KatalogCategorySubcategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesajlar': {
      id: '/mesajlar'
      path: '/mesajlar'
      fullPath: '/mesajlar'
      preLoaderRoute: typeof MesajlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yonetim': {
      id: '/yonetim'
      path: '/yonetim'
      fullPath: '/yonetim'
      preLoaderRoute: typeof YonetimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$category': {
      id: '/kategori/$category'
      path: '/kategori/$category'
      fullPath: '/kategori/$category'
      preLoaderRoute: typeof KategoriCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urun/$productId': {
      id: '/urun/$productId'
      path: '/urun/$productId'
      fullPath: '/urun/$productId'
      preLoaderRoute: typeof UrunProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog/$category/$subcategory': {
      id: '/katalog/$category/$subcategory'
      path: '/katalog/$category/$subcategory'
      fullPath: '/katalog/$category/$subcategory'
      preLoaderRoute: typeof KatalogCategorySubcategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MesajlarRoute: MesajlarRoute,
  YonetimRoute: YonetimRoute,
  KategoriCategoryRoute: KategoriCategoryRoute,
  UrunProductIdRoute: UrunProductIdRoute,
  KatalogCategorySubcategoryRoute: KatalogCategorySubcategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
